- name:  upgarde system from centos 7 to 8
  hosts: centos
  become: True
  remote_user: root
  tasks:
  - name: test shell
    shell: |
      ls -l
      cat /etc/resolv.conf
      date 
    register: content
  - debug:
      var: content.stdout_lines
